from typing import Callable, Dict

# Domain imports
from .anchors import move_object_anchor_to_point
from .animation import (
    clear_animation,
    delete_keyframe,
    evaluate_fcurve,
    get_current_frame,
    insert_keyframe,
    list_fcurves,
    set_animation_fps,
    set_current_frame,
    set_frame_range,
    set_keyframe_interpolation,
)
from .antenna import create_nested_cones
from .api import api_validator
from .armature import (
    add_armature_constraint,
    add_bone,
    add_ik_constraint,
    create_armature,
    create_vertex_group,
    delete_bone,
    edit_bone,
    list_bones,
    set_armature_modifier,
    skin_to_armature,
    symmetrize_bones,
)
from .booleans import boolean_tool, join_objects
from .camera import (
    camera_look_at,
    create_camera,
    get_camera_info,
    set_camera_active,
    set_camera_properties,
)
from .collections import (
    create_collection,
    isolate_in_collection,
    link_to_collection,
    list_collections,
    move_to_layer,
    remove_collection,
    unlink_from_collection,
)
from .constraints import (
    add_constraint_copy_location,
    add_constraint_copy_rotation,
    add_constraint_copy_scale,
    add_constraint_limit_location,
    clear_parent,
    list_constraints,
    remove_constraint,
    set_parent,
)
from .curves import (
    array_along_curve,
    create_curve_bezier,
    create_curve_circle,
    create_text,
    curve_to_mesh,
    set_curve_bevel,
    set_curve_extrude,
    set_curve_taper,
    set_font,
    set_text_content,
    set_text_properties,
    text_to_curve,
)
from .geometry import create_beveled_box
from .geometry_processing import (
    bridge_edge_loops,
    extrude_faces,
    inset_faces,
    recalculate_normals,
    remove_doubles,
    scale_normals,
    set_sharp_edges,
    shade_flat,
    shade_smooth,
    subdivide_mesh,
    triangulate_faces,
)
from .lighting import (
    create_light,
    set_light_properties,
    set_render_engine,
    set_render_resolution,
)
from .materials import assign_material, create_material_simple
from .modifiers import add_modifier_bevel, add_modifier_subdivision, apply_modifier
from .node_system import (
    add_node_to_group,
    add_shader_node,
    arrange_nodes,
    clear_node_tree,
    create_node_group,
    create_shader_node_tree,
    delete_node,
    get_node_info,
    link_nodes,
    set_node_group_input,
    set_node_property,
)
from .primitives import create_primitive
from .scene import delete_object, rename_object, scene_clear
from .shape_keys import (
    add_shape_key,
    delete_shape_key,
    list_shape_keys,
    rename_shape_key,
    reset_shape_keys,
    set_shape_key_range,
    set_shape_key_value,
    set_shape_key_vertex_position,
    shape_key_from_mix,
)
from .spatial import spatial_query
from .textures import (
    add_normal_map,
    add_texture_to_material,
    bake_texture,
    create_image_texture,
    import_image_texture,
    save_image,
    set_texture_mapping,
)
from .transforms import apply_transform
from .runtime_gateway import (
    data_collections_list,
    ops_introspect,
    ops_invoke,
    ops_list,
    ops_search,
    py_call,
    py_get,
    py_set,
    types_list,
)
from .uv_mapping import (
    add_uv_map,
    arrange_uvs,
    lightmap_pack,
    mark_seam,
    pack_uv_islands,
    scale_uv,
    set_active_uv_map,
    smart_project_uv,
    unwrap_mesh,
)
from .sculpting import (
    set_sculpt_brush,
    set_sculpt_symmetry,
    sculpt_draw,
    sculpt_smooth,
    sculpt_grab,
    sculpt_inflate,
    sculpt_pinch,
    sculpt_flatten,
    sculpt_crease,
    sculpt_layer,
    dyntopo_enabled,
    multires_add_level,
    multires_apply,
    remesh,
    get_sculpt_mask,
)
from .physics import (
    rigidbody_add,
    rigidbody_set_mass,
    rigidbody_set_collision_shape,
    rigidbody_connect,
    rigidbody_bake,
    cloth_add,
    cloth_pin_vertices,
    cloth_bake,
    fluid_domain_create,
    fluid_emitter_add,
    fluid_effector_add,
    fluid_bake,
    softbody_add,
    force_field_add,
    collision_add,
)
from .geometry_nodes import (
    create_geometry_nodes_tree,
    add_geometry_node,
    link_geometry_nodes,
    set_geometry_node_input,
    set_node_tree_output,
    bake_geometry_nodes,
    geometry_nodes_to_mesh,
    create_attribute,
    set_attribute_values,
    get_attribute_info,
    list_attributes,
    remove_attribute,
)
from .particles import (
    create_particle_system,
    set_particle_emitter,
    set_particle_source,
    set_particle_velocity,
    set_particle_physics,
    set_particle_gravity,
    set_particle_render,
    set_particle_hair,
    set_particle_instance_object,
    bake_particles,
    convert_particles_to_mesh,
    remove_particle_system,
    list_particle_systems,
)
from .grease_pencil import (
    gpencil_add_blank,
    gpencil_layer_create,
    gpencil_layer_remove,
    gpencil_frame_add,
    gpencil_draw_line,
    gpencil_draw_stroke,
    gpencil_fill,
    gpencil_delete_stroke,
    gpencil_material_add,
    gpencil_set_material,
    gpencil_convert_to_mesh,
    gpencil_convert_to_curve,
    set_gpencil_brush,
    gpencil_import_svg,
    gpencil_export_svg,
    gpencil_set_line_attributes,
    gpencil_set_view_layer,
    gpencil_duplicate_frame,
)
from .sequencer import (
    sequencer_create_scene,
    sequencer_add_movie_strip,
    sequencer_add_image_strip,
    sequencer_add_sound_strip,
    sequencer_add_text_strip,
    sequencer_set_strip_position,
    sequencer_delete_strip,
    sequencer_add_effect_strip,
    sequencer_set_strip_opacity,
    sequencer_set_strip_volume,
    sequencer_list_strips,
    sequencer_meta_strip_create,
)
from .tracking import (
    tracking_load_clip,
    tracking_create_track,
    tracking_track_frame,
    tracking_solve_camera,
    tracking_set_camera,
    tracking_add_plane_track,
    tracking_delete_track,
    tracking_list_tracks,
    tracking_set_track_pattern_size,
    tracking_create_object,
    tracking_create_scene_from_clip,
)
from .compositor import (
    create_compositor_tree,
    add_compositor_node,
    link_compositor_nodes,
    set_compositor_node_input,
    compositor_add_blur,
    compositor_add_color_balance,
    compositor_add_mix,
    compositor_add_bright_contrast,
    compositor_add_alpha_over,
    compositor_add_image,
    compositor_delete_node,
    compositor_clear_tree,
    compositor_list_nodes,
    set_compositor_backdrop,
)
from .drivers import (
    add_driver,
    driver_add_variable,
    driver_set_expression,
    driver_remove,
    driver_copy,
    driver_list,
    driver_add_shape_key,
)
from .asset import (
    asset_mark,
    asset_clear,
    asset_set_metadata,
    asset_list,
    library_append,
    library_link,
    library_reload,
    library_list,
    pack_blend,
    unpack_blend,
    make_paths_absolute,
    make_paths_relative,
    find_missing_files,
    report_missing_files,
)
from .painting import (
    set_texture_paint_brush,
    texture_paint_mode,
    quick_paint,
    image_paint_slot,
    paint_image,
    texture_paint_fill,
    set_paint_symmetry,
    paint_operator_enable,
    clone_from_image,
    project_paint,
    uv_texture_paint_prep,
    vertex_paint_mode,
    set_vertex_paint_brush,
    vertex_paint_fill,
    weight_paint_mode,
    set_weight_paint_brush,
    weight_paint_set,
)
from .rendering import (
    render_image,
    set_render_engine,
    set_render_resolution,
    set_frame_range,
    export_obj,
    export_fbx,
    export_gltf,
    import_obj,
    import_fbx,
    import_gltf,
    set_render_output,
    enable_pass,
    set_cycles_samples,
    set_cycles_denoise,
    set_eevee_samples,
)

SKILL_REGISTRY: Dict[str, Callable] = {
    # Scene / objects
    "scene_clear": scene_clear,
    "delete_object": delete_object,
    "rename_object": rename_object,

    # Geometry
    "create_primitive": create_primitive,
    "create_beveled_box": create_beveled_box,
    "create_nested_cones": create_nested_cones,

    # Geometry Processing
    "extrude_faces": extrude_faces,
    "inset_faces": inset_faces,
    "subdivide_mesh": subdivide_mesh,
    "triangulate_faces": triangulate_faces,
    "remove_doubles": remove_doubles,
    "recalculate_normals": recalculate_normals,
    "scale_normals": scale_normals,
    "shade_smooth": shade_smooth,
    "shade_flat": shade_flat,
    "set_sharp_edges": set_sharp_edges,
    "bridge_edge_loops": bridge_edge_loops,

    # UV Mapping
    "unwrap_mesh": unwrap_mesh,
    "smart_project_uv": smart_project_uv,
    "lightmap_pack": lightmap_pack,
    "mark_seam": mark_seam,
    "pack_uv_islands": pack_uv_islands,
    "scale_uv": scale_uv,
    "arrange_uvs": arrange_uvs,
    "add_uv_map": add_uv_map,
    "set_active_uv_map": set_active_uv_map,

    # Textures
    "import_image_texture": import_image_texture,
    "create_image_texture": create_image_texture,
    "add_texture_to_material": add_texture_to_material,
    "set_texture_mapping": set_texture_mapping,
    "add_normal_map": add_normal_map,
    "bake_texture": bake_texture,
    "save_image": save_image,

    # Curves
    "create_curve_bezier": create_curve_bezier,
    "create_curve_circle": create_curve_circle,
    "create_text": create_text,
    "set_text_content": set_text_content,
    "set_text_properties": set_text_properties,
    "set_curve_bevel": set_curve_bevel,
    "set_curve_taper": set_curve_taper,
    "set_curve_extrude": set_curve_extrude,
    "array_along_curve": array_along_curve,
    "curve_to_mesh": curve_to_mesh,
    "text_to_curve": text_to_curve,
    "set_font": set_font,

    # Transforms & spatial awareness
    "apply_transform": apply_transform,
    "spatial_query": spatial_query,
    "move_object_anchor_to_point": move_object_anchor_to_point,

    # Booleans / composition
    "boolean_tool": boolean_tool,
    "join_objects": join_objects,

    # Materials
    "create_material_simple": create_material_simple,
    "assign_material": assign_material,

    # Modifiers
    "add_modifier_bevel": add_modifier_bevel,
    "add_modifier_subdivision": add_modifier_subdivision,
    "apply_modifier": apply_modifier,

    # Node System
    "create_shader_node_tree": create_shader_node_tree,
    "add_shader_node": add_shader_node,
    "link_nodes": link_nodes,
    "set_node_property": set_node_property,
    "get_node_info": get_node_info,
    "delete_node": delete_node,
    "create_node_group": create_node_group,
    "add_node_to_group": add_node_to_group,
    "set_node_group_input": set_node_group_input,
    "clear_node_tree": clear_node_tree,
    "arrange_nodes": arrange_nodes,

    # Lighting
    "create_light": create_light,
    "set_light_properties": set_light_properties,
    "set_render_engine": set_render_engine,
    "set_render_resolution": set_render_resolution,

    # Camera
    "create_camera": create_camera,
    "set_camera_active": set_camera_active,
    "set_camera_properties": set_camera_properties,
    "camera_look_at": camera_look_at,
    "get_camera_info": get_camera_info,

    # Collections
    "create_collection": create_collection,
    "link_to_collection": link_to_collection,
    "unlink_from_collection": unlink_from_collection,
    "remove_collection": remove_collection,
    "list_collections": list_collections,
    "isolate_in_collection": isolate_in_collection,
    "move_to_layer": move_to_layer,

    # Constraints & Parenting
    "set_parent": set_parent,
    "clear_parent": clear_parent,
    "add_constraint_copy_location": add_constraint_copy_location,
    "add_constraint_copy_rotation": add_constraint_copy_rotation,
    "add_constraint_copy_scale": add_constraint_copy_scale,
    "add_constraint_limit_location": add_constraint_limit_location,
    "remove_constraint": remove_constraint,
    "list_constraints": list_constraints,

    # Armature & Rigging
    "create_armature": create_armature,
    "add_bone": add_bone,
    "edit_bone": edit_bone,
    "delete_bone": delete_bone,
    "list_bones": list_bones,
    "create_vertex_group": create_vertex_group,
    "skin_to_armature": skin_to_armature,
    "set_armature_modifier": set_armature_modifier,
    "add_ik_constraint": add_ik_constraint,
    "add_armature_constraint": add_armature_constraint,
    "symmetrize_bones": symmetrize_bones,

    # Shape Keys
    "add_shape_key": add_shape_key,
    "set_shape_key_value": set_shape_key_value,
    "set_shape_key_range": set_shape_key_range,
    "delete_shape_key": delete_shape_key,
    "rename_shape_key": rename_shape_key,
    "list_shape_keys": list_shape_keys,
    "reset_shape_keys": reset_shape_keys,
    "shape_key_from_mix": shape_key_from_mix,
    "set_shape_key_vertex_position": set_shape_key_vertex_position,

    # Animation
    "insert_keyframe": insert_keyframe,
    "delete_keyframe": delete_keyframe,
    "set_current_frame": set_current_frame,
    "get_current_frame": get_current_frame,
    "set_frame_range": set_frame_range,
    "set_animation_fps": set_animation_fps,
    "clear_animation": clear_animation,
    "list_fcurves": list_fcurves,
    "set_keyframe_interpolation": set_keyframe_interpolation,
    "evaluate_fcurve": evaluate_fcurve,

    # API validation
    "api_validator": api_validator,

    # Sculpting
    "set_sculpt_brush": set_sculpt_brush,
    "set_sculpt_symmetry": set_sculpt_symmetry,
    "sculpt_draw": sculpt_draw,
    "sculpt_smooth": sculpt_smooth,
    "sculpt_grab": sculpt_grab,
    "sculpt_inflate": sculpt_inflate,
    "sculpt_pinch": sculpt_pinch,
    "sculpt_flatten": sculpt_flatten,
    "sculpt_crease": sculpt_crease,
    "sculpt_layer": sculpt_layer,
    "dyntopo_enabled": dyntopo_enabled,
    "multires_add_level": multires_add_level,
    "multires_apply": multires_apply,
    "remesh": remesh,
    "get_sculpt_mask": get_sculpt_mask,

    # Physics
    "rigidbody_add": rigidbody_add,
    "rigidbody_set_mass": rigidbody_set_mass,
    "rigidbody_set_collision_shape": rigidbody_set_collision_shape,
    "rigidbody_connect": rigidbody_connect,
    "rigidbody_bake": rigidbody_bake,
    "cloth_add": cloth_add,
    "cloth_pin_vertices": cloth_pin_vertices,
    "cloth_bake": cloth_bake,
    "fluid_domain_create": fluid_domain_create,
    "fluid_emitter_add": fluid_emitter_add,
    "fluid_effector_add": fluid_effector_add,
    "fluid_bake": fluid_bake,
    "softbody_add": softbody_add,
    "force_field_add": force_field_add,
    "collision_add": collision_add,

    # Geometry Nodes
    "create_geometry_nodes_tree": create_geometry_nodes_tree,
    "add_geometry_node": add_geometry_node,
    "link_geometry_nodes": link_geometry_nodes,
    "set_geometry_node_input": set_geometry_node_input,
    "set_node_tree_output": set_node_tree_output,
    "bake_geometry_nodes": bake_geometry_nodes,
    "geometry_nodes_to_mesh": geometry_nodes_to_mesh,
    "create_attribute": create_attribute,
    "set_attribute_values": set_attribute_values,
    "get_attribute_info": get_attribute_info,
    "list_attributes": list_attributes,
    "remove_attribute": remove_attribute,

    # Particle Systems
    "create_particle_system": create_particle_system,
    "set_particle_emitter": set_particle_emitter,
    "set_particle_source": set_particle_source,
    "set_particle_velocity": set_particle_velocity,
    "set_particle_physics": set_particle_physics,
    "set_particle_gravity": set_particle_gravity,
    "set_particle_render": set_particle_render,
    "set_particle_hair": set_particle_hair,
    "set_particle_instance_object": set_particle_instance_object,
    "bake_particles": bake_particles,
    "convert_particles_to_mesh": convert_particles_to_mesh,
    "remove_particle_system": remove_particle_system,
    "list_particle_systems": list_particle_systems,

    # Grease Pencil
    "gpencil_add_blank": gpencil_add_blank,
    "gpencil_layer_create": gpencil_layer_create,
    "gpencil_layer_remove": gpencil_layer_remove,
    "gpencil_frame_add": gpencil_frame_add,
    "gpencil_draw_line": gpencil_draw_line,
    "gpencil_draw_stroke": gpencil_draw_stroke,
    "gpencil_fill": gpencil_fill,
    "gpencil_delete_stroke": gpencil_delete_stroke,
    "gpencil_material_add": gpencil_material_add,
    "gpencil_set_material": gpencil_set_material,
    "gpencil_convert_to_mesh": gpencil_convert_to_mesh,
    "gpencil_convert_to_curve": gpencil_convert_to_curve,
    "set_gpencil_brush": set_gpencil_brush,
    "gpencil_import_svg": gpencil_import_svg,
    "gpencil_export_svg": gpencil_export_svg,
    "gpencil_set_line_attributes": gpencil_set_line_attributes,
    "gpencil_set_view_layer": gpencil_set_view_layer,
    "gpencil_duplicate_frame": gpencil_duplicate_frame,

    # Video Sequencer
    "sequencer_create_scene": sequencer_create_scene,
    "sequencer_add_movie_strip": sequencer_add_movie_strip,
    "sequencer_add_image_strip": sequencer_add_image_strip,
    "sequencer_add_sound_strip": sequencer_add_sound_strip,
    "sequencer_add_text_strip": sequencer_add_text_strip,
    "sequencer_set_strip_position": sequencer_set_strip_position,
    "sequencer_delete_strip": sequencer_delete_strip,
    "sequencer_add_effect_strip": sequencer_add_effect_strip,
    "sequencer_set_strip_opacity": sequencer_set_strip_opacity,
    "sequencer_set_strip_volume": sequencer_set_strip_volume,
    "sequencer_list_strips": sequencer_list_strips,
    "sequencer_meta_strip_create": sequencer_meta_strip_create,

    # Motion Tracking
    "tracking_load_clip": tracking_load_clip,
    "tracking_create_track": tracking_create_track,
    "tracking_track_frame": tracking_track_frame,
    "tracking_solve_camera": tracking_solve_camera,
    "tracking_set_camera": tracking_set_camera,
    "tracking_add_plane_track": tracking_add_plane_track,
    "tracking_delete_track": tracking_delete_track,
    "tracking_list_tracks": tracking_list_tracks,
    "tracking_set_track_pattern_size": tracking_set_track_pattern_size,
    "tracking_create_object": tracking_create_object,
    "tracking_create_scene_from_clip": tracking_create_scene_from_clip,

    # Compositor Nodes
    "create_compositor_tree": create_compositor_tree,
    "add_compositor_node": add_compositor_node,
    "link_compositor_nodes": link_compositor_nodes,
    "set_compositor_node_input": set_compositor_node_input,
    "compositor_add_blur": compositor_add_blur,
    "compositor_add_color_balance": compositor_add_color_balance,
    "compositor_add_mix": compositor_add_mix,
    "compositor_add_bright_contrast": compositor_add_bright_contrast,
    "compositor_add_alpha_over": compositor_add_alpha_over,
    "compositor_add_image": compositor_add_image,
    "compositor_delete_node": compositor_delete_node,
    "compositor_clear_tree": compositor_clear_tree,
    "compositor_list_nodes": compositor_list_nodes,
    "set_compositor_backdrop": set_compositor_backdrop,

    # Drivers
    "add_driver": add_driver,
    "driver_add_variable": driver_add_variable,
    "driver_set_expression": driver_set_expression,
    "driver_remove": driver_remove,
    "driver_copy": driver_copy,
    "driver_list": driver_list,
    "driver_add_shape_key": driver_add_shape_key,

    # Asset Management
    "asset_mark": asset_mark,
    "asset_clear": asset_clear,
    "asset_set_metadata": asset_set_metadata,
    "asset_list": asset_list,
    "library_append": library_append,
    "library_link": library_link,
    "library_reload": library_reload,
    "library_list": library_list,
    "pack_blend": pack_blend,
    "unpack_blend": unpack_blend,
    "make_paths_absolute": make_paths_absolute,
    "make_paths_relative": make_paths_relative,
    "find_missing_files": find_missing_files,
    "report_missing_files": report_missing_files,

    # Painting
    "set_texture_paint_brush": set_texture_paint_brush,
    "texture_paint_mode": texture_paint_mode,
    "quick_paint": quick_paint,
    "image_paint_slot": image_paint_slot,
    "paint_image": paint_image,
    "texture_paint_fill": texture_paint_fill,
    "set_paint_symmetry": set_paint_symmetry,
    "paint_operator_enable": paint_operator_enable,
    "clone_from_image": clone_from_image,
    "project_paint": project_paint,
    "uv_texture_paint_prep": uv_texture_paint_prep,
    "vertex_paint_mode": vertex_paint_mode,
    "set_vertex_paint_brush": set_vertex_paint_brush,
    "vertex_paint_fill": vertex_paint_fill,
    "weight_paint_mode": weight_paint_mode,
    "set_weight_paint_brush": set_weight_paint_brush,
    "weight_paint_set": weight_paint_set,

    # Rendering
    "render_image": render_image,
    "set_render_engine": set_render_engine,
    "set_render_resolution": set_render_resolution,
    "set_frame_range": set_frame_range,
    "export_obj": export_obj,
    "export_fbx": export_fbx,
    "export_gltf": export_gltf,
    "import_obj": import_obj,
    "import_fbx": import_fbx,
    "import_gltf": import_gltf,
    "set_render_output": set_render_output,
    "enable_pass": enable_pass,
    "set_cycles_samples": set_cycles_samples,
    "set_cycles_denoise": set_cycles_denoise,
    "set_eevee_samples": set_eevee_samples,

    # Full Blender API coverage gateway
    "py_get": py_get,
    "py_set": py_set,
    "py_call": py_call,
    "ops_list": ops_list,
    "ops_search": ops_search,
    "ops_invoke": ops_invoke,
    "ops_introspect": ops_introspect,
    "types_list": types_list,
    "data_collections_list": data_collections_list,
}

# Metadata for documentation
SKILL_CATEGORIES = {
    "Scene": ["scene_clear", "delete_object", "rename_object"],
    "Primitives": ["create_primitive", "create_beveled_box", "create_nested_cones"],
    "Geometry Processing": ["extrude_faces", "inset_faces", "subdivide_mesh", "triangulate_faces", "remove_doubles", "recalculate_normals", "scale_normals", "shade_smooth", "shade_flat", "set_sharp_edges", "bridge_edge_loops"],
    "UV Mapping": ["unwrap_mesh", "smart_project_uv", "lightmap_pack", "mark_seam", "pack_uv_islands", "scale_uv", "arrange_uvs", "add_uv_map", "set_active_uv_map"],
    "Textures": ["import_image_texture", "create_image_texture", "add_texture_to_material", "set_texture_mapping", "add_normal_map", "bake_texture", "save_image"],
    "Curves & Text": ["create_curve_bezier", "create_curve_circle", "create_text", "set_text_content", "set_text_properties", "set_curve_bevel", "set_curve_taper", "set_curve_extrude", "array_along_curve", "curve_to_mesh", "text_to_curve", "set_font"],
    "Transforms": ["apply_transform", "spatial_query", "move_object_anchor_to_point"],
    "Booleans": ["boolean_tool", "join_objects"],
    "Materials": ["create_material_simple", "assign_material"],
    "Node System": ["create_shader_node_tree", "add_shader_node", "link_nodes", "set_node_property", "get_node_info", "delete_node", "create_node_group", "add_node_to_group", "set_node_group_input", "clear_node_tree", "arrange_nodes"],
    "Modifiers": ["add_modifier_bevel", "add_modifier_subdivision", "apply_modifier"],
    "Lighting": ["create_light", "set_light_properties"],
    "Camera": ["create_camera", "set_camera_active", "set_camera_properties", "camera_look_at", "get_camera_info"],
    "Collections": ["create_collection", "link_to_collection", "unlink_from_collection", "remove_collection", "list_collections", "isolate_in_collection", "move_to_layer"],
    "Constraints": ["set_parent", "clear_parent", "add_constraint_copy_location", "add_constraint_copy_rotation", "add_constraint_copy_scale", "add_constraint_limit_location", "remove_constraint", "list_constraints"],
    "Armature & Rigging": ["create_armature", "add_bone", "edit_bone", "delete_bone", "list_bones", "create_vertex_group", "skin_to_armature", "set_armature_modifier", "add_ik_constraint", "add_armature_constraint", "symmetrize_bones"],
    "Shape Keys": ["add_shape_key", "set_shape_key_value", "set_shape_key_range", "delete_shape_key", "rename_shape_key", "list_shape_keys", "reset_shape_keys", "shape_key_from_mix", "set_shape_key_vertex_position"],
    "Animation": ["insert_keyframe", "delete_keyframe", "set_current_frame", "get_current_frame", "set_frame_range", "set_animation_fps", "clear_animation", "list_fcurves", "set_keyframe_interpolation", "evaluate_fcurve"],
    "Sculpting": ["set_sculpt_brush", "set_sculpt_symmetry", "sculpt_draw", "sculpt_smooth", "sculpt_grab", "sculpt_inflate", "sculpt_pinch", "sculpt_flatten", "sculpt_crease", "sculpt_layer", "dyntopo_enabled", "multires_add_level", "multires_apply", "remesh", "get_sculpt_mask"],
    "Physics": ["rigidbody_add", "rigidbody_set_mass", "rigidbody_set_collision_shape", "rigidbody_connect", "rigidbody_bake", "cloth_add", "cloth_pin_vertices", "cloth_bake", "fluid_domain_create", "fluid_emitter_add", "fluid_effector_add", "fluid_bake", "softbody_add", "force_field_add", "collision_add"],
    "Geometry Nodes": ["create_geometry_nodes_tree", "add_geometry_node", "link_geometry_nodes", "set_geometry_node_input", "set_node_tree_output", "bake_geometry_nodes", "geometry_nodes_to_mesh", "create_attribute", "set_attribute_values", "get_attribute_info", "list_attributes", "remove_attribute"],
    "Particle Systems": ["create_particle_system", "set_particle_emitter", "set_particle_source", "set_particle_velocity", "set_particle_physics", "set_particle_gravity", "set_particle_render", "set_particle_hair", "set_particle_instance_object", "bake_particles", "convert_particles_to_mesh", "remove_particle_system", "list_particle_systems"],
    "Grease Pencil": ["gpencil_add_blank", "gpencil_layer_create", "gpencil_layer_remove", "gpencil_frame_add", "gpencil_draw_line", "gpencil_draw_stroke", "gpencil_fill", "gpencil_delete_stroke", "gpencil_material_add", "gpencil_set_material", "gpencil_convert_to_mesh", "gpencil_convert_to_curve", "set_gpencil_brush", "gpencil_import_svg", "gpencil_export_svg", "gpencil_set_line_attributes", "gpencil_set_view_layer", "gpencil_duplicate_frame"],
    "Video Sequencer": ["sequencer_create_scene", "sequencer_add_movie_strip", "sequencer_add_image_strip", "sequencer_add_sound_strip", "sequencer_add_text_strip", "sequencer_set_strip_position", "sequencer_delete_strip", "sequencer_add_effect_strip", "sequencer_set_strip_opacity", "sequencer_set_strip_volume", "sequencer_list_strips", "sequencer_meta_strip_create"],
    "Motion Tracking": ["tracking_load_clip", "tracking_create_track", "tracking_track_frame", "tracking_solve_camera", "tracking_set_camera", "tracking_add_plane_track", "tracking_delete_track", "tracking_list_tracks", "tracking_set_track_pattern_size", "tracking_create_object", "tracking_create_scene_from_clip"],
    "Compositor": ["create_compositor_tree", "add_compositor_node", "link_compositor_nodes", "set_compositor_node_input", "compositor_add_blur", "compositor_add_color_balance", "compositor_add_mix", "compositor_add_bright_contrast", "compositor_add_alpha_over", "compositor_add_image", "compositor_delete_node", "compositor_clear_tree", "compositor_list_nodes", "set_compositor_backdrop"],
    "Drivers": ["add_driver", "driver_add_variable", "driver_set_expression", "driver_remove", "driver_copy", "driver_list", "driver_add_shape_key"],
    "Asset Management": ["asset_mark", "asset_clear", "asset_set_metadata", "asset_list", "library_append", "library_link", "library_reload", "library_list", "pack_blend", "unpack_blend", "make_paths_absolute", "make_paths_relative", "find_missing_files", "report_missing_files"],
    "Painting": ["set_texture_paint_brush", "texture_paint_mode", "quick_paint", "image_paint_slot", "paint_image", "texture_paint_fill", "set_paint_symmetry", "paint_operator_enable", "clone_from_image", "project_paint", "uv_texture_paint_prep", "vertex_paint_mode", "set_vertex_paint_brush", "vertex_paint_fill", "weight_paint_mode", "set_weight_paint_brush", "weight_paint_set"],
    "Rendering & IO": ["render_image", "set_render_engine", "set_render_resolution", "set_frame_range", "export_obj", "export_fbx", "export_gltf", "import_obj", "import_fbx", "import_gltf", "set_render_output", "enable_pass", "set_cycles_samples", "set_cycles_denoise", "set_eevee_samples"],
    "Gateway": ["py_get", "py_set", "py_call", "ops_list", "ops_search", "ops_invoke", "ops_introspect", "types_list", "data_collections_list", "api_validator"],
}

SKILL_COUNT = len(SKILL_REGISTRY)
CATEGORY_COUNT = len(SKILL_CATEGORIES)
